Q1: 
	python3 Q1/plot.py $1 $2
Q2:
	./Q2/gSpan -f Q2/formatted.txt  -s 0.5 -o -i
	g++ ./Q2/index.cpp -o ./Q2/index
	./Q2/index 0.5 1
	g++ ./Q2/query.cpp -o ./Q2/query
	./Q2/query query.txt output_2019CS10368.txt

Q3:
	python3 Q3/elbow_plot.py $1
