name: gnn
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - cryptography
  - cudatoolkit
  - cycler
  - dbus
  - expat
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - gettext
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - intel-openmp
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libdeflate
  - libedit
  - libevent
  - libffi
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libiconv
  - liblapack
  - libllvm13
  - libogg
  - libopus
  - libpng
  - libpq
  - libsqlite
  - libtiff
  - libuuid
  - libvorbis
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mkl
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - networkx
  - nspr
  - nss
  - numexpr
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - pthread-stubs
  - pycparser
  - pyg
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-cluster
  - pytorch-mutex
  - pytorch-scatter
  - pytorch-sparse
  - pytz
  - qt
  - readline
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - typing-extensions
  - typing_extensions
  - unicodedata2
  - urllib3
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zlib
  - zstd
  - pip:
    - pyqt5-sip
    - pyqtchart
    - pyqtwebengine
